---
label: Site Config
hide_body: true
fields:
- name: site_name
  type: text
  config:
    required: false
  label: Site Name
- type: text
  name: description
  label: Site Description
- type: text
  name: artist
  label: Artist Name
- name: profile_image
  type: file
  config:
    maxSize: 250
  label: Profile Image
- name: hero_title
  type: text
  config:
    required: false
  label: Hero Title
- name: hero_subtitle
  type: text
  config:
    required: false
  label: Hero Subtitle
- type: field_group
  name: contact
  label: Contact Info
  fields:
  - type: text
    name: email
    label: Email
  - type: text
    name: twitter_handle
    label: Twitter Profile
  - type: text
    name: instagram_handle
    label: Instagram Profile
- type: text
  name: primary_color
  label: Primary Color
- type: text
  name: repository_url
  label: Github Repo
- name: footer
  type: text
  config:
    required: false
  label: Footer
pages:
- src/assets/content/data/config.json
