---
label: Site Config
hide_body: true
fields:
- name: site_name
  type: text
  config:
    required: false
  label: Site Name
- type: text
  name: artist
  label: artist
- type: text
  name: description
  label: description
- name: hero_title
  type: text
  config:
    required: false
  label: Hero Title
- name: hero_subtitle
  type: text
  config:
    required: false
  label: Hero Subtitle
- type: field_group
  name: contact
  label: contact
  fields:
  - type: text
    name: email
    label: email
  - type: text
    name: twitter_handle
    label: twitter_handle
  - type: text
    name: instagram_handle
    label: instagram_handle
- type: text
  name: primary_color
  label: primary_color
- type: text
  name: repository_url
  label: repository_url
- name: footer
  type: text
  config:
    required: false
  label: Footer
pages:
- src/assets/content/data/config.json
